# Name undefined
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-456-7890"
}
###

# Number undefined
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jane Doe"
}
###

# Duplicate name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "123-456-7890"
}