# Create new person
POST https://ashero-full-stack-open-part3.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Jane Doe",
  "number": "123-456-7890"
}
###

# Check persons list
GET https://ashero-full-stack-open-part3.fly.dev/api/persons